// S&P 500 + NASDAQ 100 + Russell 2000 popular names + ETFs + top crypto + major forex pairs + other US-listed stocks
// For any ticker NOT found here, app.js falls back to Finnhub /stock/profile2
const SECTOR_MAP = {

  // ── Technology ──
  AAPL:'Technology', MSFT:'Technology', NVDA:'Technology', AVGO:'Technology',
  ORCL:'Technology', CSCO:'Technology', ADBE:'Technology', QCOM:'Technology',
  AMD:'Technology',  TXN:'Technology',  INTC:'Technology', IBM:'Technology',
  MU:'Technology',   AMAT:'Technology', LRCX:'Technology', KLAC:'Technology',
  ADI:'Technology',  MCHP:'Technology', NXPI:'Technology', STX:'Technology',
  WDC:'Technology',  HPQ:'Technology',  HPE:'Technology',  ACN:'Technology',
  INTU:'Technology', PAYX:'Technology', ADP:'Technology',  CDNS:'Technology',
  SNPS:'Technology', ANSS:'Technology', PTC:'Technology',  EPAM:'Technology',
  AKAM:'Technology', FFIV:'Technology', ENPH:'Technology', MPWR:'Technology',
  SWKS:'Technology', KEYS:'Technology', TRMB:'Technology', CDW:'Technology',
  CTSH:'Technology', IT:'Technology',   GEN:'Technology',  GDDY:'Technology',
  NET:'Technology',  PANW:'Technology', CRWD:'Technology', FTNT:'Technology',
  ZS:'Technology',   OKTA:'Technology', DDOG:'Technology', SNOW:'Technology',
  PLTR:'Technology', HUBS:'Technology', VEEV:'Technology', CRM:'Technology',
  NOW:'Technology',  WDAY:'Technology', MDB:'Technology',  SPLK:'Technology',
  PSTG:'Technology', TEAM:'Technology', BILL:'Technology', ESTC:'Technology',
  DOCU:'Technology', ZM:'Technology',   FSLR:'Technology', ROP:'Technology',
  JNPR:'Technology', NTAP:'Technology', TDY:'Technology',  ZBRA:'Technology',
  FIS:'Technology',  FISV:'Technology', WU:'Technology',   BR:'Technology',
  UBER:'Technology', LYFT:'Technology', DASH:'Technology', ABNB:'Technology',
  TWLO:'Technology', GLOB:'Technology', GTLB:'Technology', CFLT:'Technology',
  MNDY:'Technology', SMAR:'Technology', APPN:'Technology', FROG:'Technology',
  SUMO:'Technology', VMEO:'Technology', BOX:'Technology',  DROPBOX:'Technology',
  DBX:'Technology',  QLYS:'Technology', TENB:'Technology', RPD:'Technology',
  VRNS:'Technology', ASAN:'Technology', COUP:'Technology', PCTY:'Technology',
  PAYC:'Technology', SPSN:'Technology', JAMF:'Technology', PWSC:'Technology',
  ALTR:'Technology', CLDR:'Technology', HCP:'Technology',  ALRM:'Technology',
  QTWO:'Technology', NCNO:'Technology', CWAN:'Technology', EVTC:'Technology',
  PEGA:'Technology', PRFT:'Technology', EXLS:'Technology', EPIQ:'Technology',
  CDRE:'Technology', AGYS:'Technology', VNET:'Technology', WEX:'Technology',
  CDAY:'Technology', TOST:'Technology', PAR:'Technology',  RAMP:'Technology',
  FOUR:'Technology', RELY:'Technology', FLYW:'Technology', RELY:'Technology',
  SEON:'Technology', NUVL:'Technology', AIOT:'Technology', FRSH:'Technology',
  S:'Technology',    INTA:'Technology', AMPL:'Technology', BRZE:'Technology',
  SEMR:'Technology', SPSC:'Technology', MSTR:'Technology', COIN:'Technology',
  MARA:'Technology', RIOT:'Technology', CLSK:'Technology', HUT:'Technology',
  BTBT:'Technology', CIFR:'Technology', IREN:'Technology', CORZ:'Technology',

  // ── Communication Services ──
  GOOG:'Communication', GOOGL:'Communication', META:'Communication',
  NFLX:'Communication', DIS:'Communication',   CMCSA:'Communication',
  T:'Communication',    VZ:'Communication',    TMUS:'Communication',
  CHTR:'Communication', PARA:'Communication',  WBD:'Communication',
  FOX:'Communication',  FOXA:'Communication',  NYT:'Communication',
  LYV:'Communication',  TTWO:'Communication',  EA:'Communication',
  RBLX:'Communication', SNAP:'Communication',  PINS:'Communication',
  SPOT:'Communication', ROKU:'Communication',  IAC:'Communication',
  ANGI:'Communication', MTCH:'Communication',  BMBL:'Communication',
  ZETA:'Communication', IAS:'Communication',   TBLA:'Communication',
  MGNI:'Communication', TTD:'Communication',   PUBM:'Communication',
  APPS:'Communication', DV:'Communication',    STGW:'Communication',
  LKFN:'Communication', LUMN:'Communication',  ATEX:'Communication',
  SIRI:'Communication', LSXMA:'Communication', LSXMK:'Communication',
  FWONA:'Communication', FWONK:'Communication', BATRK:'Communication',
  IDT:'Communication',  GOGO:'Communication',  ATNI:'Communication',
  ATUS:'Communication', LBRDA:'Communication', LBRDK:'Communication',
  TKC:'Communication',  LILAK:'Communication', TIGO:'Communication',

  // ── Consumer Discretionary ──
  AMZN:'Consumer Disc', TSLA:'Consumer Disc', HD:'Consumer Disc',
  MCD:'Consumer Disc',  NKE:'Consumer Disc',  LOW:'Consumer Disc',
  SBUX:'Consumer Disc', TJX:'Consumer Disc',  BKNG:'Consumer Disc',
  CMG:'Consumer Disc',  MAR:'Consumer Disc',  HLT:'Consumer Disc',
  GM:'Consumer Disc',   F:'Consumer Disc',    RIVN:'Consumer Disc',
  LCID:'Consumer Disc', LVS:'Consumer Disc',  WYNN:'Consumer Disc',
  MGM:'Consumer Disc',  CZR:'Consumer Disc',  RCL:'Consumer Disc',
  CCL:'Consumer Disc',  NCLH:'Consumer Disc', EXPE:'Consumer Disc',
  EBAY:'Consumer Disc', ETSY:'Consumer Disc', LULU:'Consumer Disc',
  ROST:'Consumer Disc', BURL:'Consumer Disc', TGT:'Consumer Disc',
  ANF:'Consumer Disc',  AEO:'Consumer Disc',  GPS:'Consumer Disc',
  URBN:'Consumer Disc', CPRI:'Consumer Disc', TPR:'Consumer Disc',
  PVH:'Consumer Disc',  RL:'Consumer Disc',   VFC:'Consumer Disc',
  UAA:'Consumer Disc',  UA:'Consumer Disc',   BBY:'Consumer Disc',
  ORLY:'Consumer Disc', AZO:'Consumer Disc',  TSCO:'Consumer Disc',
  DG:'Consumer Disc',   DLTR:'Consumer Disc', W:'Consumer Disc',
  CVNA:'Consumer Disc', KMX:'Consumer Disc',  AN:'Consumer Disc',
  PAG:'Consumer Disc',  LAD:'Consumer Disc',  ABG:'Consumer Disc',
  SAH:'Consumer Disc',  GPI:'Consumer Disc',  RUSHA:'Consumer Disc',
  LKQ:'Consumer Disc',  APTV:'Consumer Disc', LEA:'Consumer Disc',
  BWA:'Consumer Disc',  GNTX:'Consumer Disc', MODG:'Consumer Disc',
  GOLF:'Consumer Disc', ONEW:'Consumer Disc', MPW:'Consumer Disc',
  SBH:'Consumer Disc',  PRTY:'Consumer Disc', WOOF:'Consumer Disc',
  CHWY:'Consumer Disc', BARK:'Consumer Disc', PETS:'Consumer Disc',
  YETI:'Consumer Disc', WEBR:'Consumer Disc', PTON:'Consumer Disc',
  NXST:'Consumer Disc', MSGS:'Consumer Disc', MSGE:'Consumer Disc',
  SIX:'Consumer Disc',  FUN:'Consumer Disc',  SEAS:'Consumer Disc',
  PLNT:'Consumer Disc', XPOF:'Consumer Disc', VNET:'Consumer Disc',
  WING:'Consumer Disc', SHAK:'Consumer Disc', TXRH:'Consumer Disc',
  DRI:'Consumer Disc',  EAT:'Consumer Disc',  DPZ:'Consumer Disc',
  YUM:'Consumer Disc',  QSR:'Consumer Disc',  JACK:'Consumer Disc',
  DENN:'Consumer Disc', CAKE:'Consumer Disc', BLMN:'Consumer Disc',
  TACO:'Consumer Disc', NURO:'Consumer Disc', FRGI:'Consumer Disc',
  RRGB:'Consumer Disc', BJRI:'Consumer Disc', CBRL:'Consumer Disc',
  PLAY:'Consumer Disc', DAVE:'Consumer Disc', FAT:'Consumer Disc',

  // ── Consumer Staples ──
  WMT:'Consumer Staples', COST:'Consumer Staples', PG:'Consumer Staples',
  KO:'Consumer Staples',  PEP:'Consumer Staples',  PM:'Consumer Staples',
  MO:'Consumer Staples',  MDLZ:'Consumer Staples', KHC:'Consumer Staples',
  GIS:'Consumer Staples', K:'Consumer Staples',    CPB:'Consumer Staples',
  CAG:'Consumer Staples', SJM:'Consumer Staples',  HRL:'Consumer Staples',
  MKC:'Consumer Staples', CLX:'Consumer Staples',  CL:'Consumer Staples',
  CHD:'Consumer Staples', EL:'Consumer Staples',   ULTA:'Consumer Staples',
  SYY:'Consumer Staples', ADM:'Consumer Staples',  BG:'Consumer Staples',
  STZ:'Consumer Staples', TAP:'Consumer Staples',  SAM:'Consumer Staples',
  KDP:'Consumer Staples', MNST:'Consumer Staples', CELH:'Consumer Staples',
  FIZZ:'Consumer Staples',COKE:'Consumer Staples', KO:'Consumer Staples',
  EMBOTELL:'Consumer Staples', BF:'Consumer Staples', BFA:'Consumer Staples',
  BFB:'Consumer Staples', DEO:'Consumer Staples',  BTI:'Consumer Staples',
  UL:'Consumer Staples',  NSRGY:'Consumer Staples',RBGLY:'Consumer Staples',
  BRGR:'Consumer Staples',HAIN:'Consumer Staples', SPAR:'Consumer Staples',
  UNFI:'Consumer Staples',SFM:'Consumer Staples',  GO:'Consumer Staples',
  CASY:'Consumer Staples',WEIS:'Consumer Staples', INGR:'Consumer Staples',
  THS:'Consumer Staples', POST:'Consumer Staples', LANC:'Consumer Staples',
  JJSF:'Consumer Staples',FRPT:'Consumer Staples', ANDE:'Consumer Staples',
  SPTN:'Consumer Staples',PFGC:'Consumer Staples',

  // ── Healthcare ──
  JNJ:'Healthcare',  UNH:'Healthcare',  LLY:'Healthcare',  ABBV:'Healthcare',
  MRK:'Healthcare',  PFE:'Healthcare',  TMO:'Healthcare',  ABT:'Healthcare',
  DHR:'Healthcare',  BMY:'Healthcare',  AMGN:'Healthcare', GILD:'Healthcare',
  CVS:'Healthcare',  MDT:'Healthcare',  SYK:'Healthcare',  BSX:'Healthcare',
  ELV:'Healthcare',  HUM:'Healthcare',  CI:'Healthcare',   CNC:'Healthcare',
  MOH:'Healthcare',  ISRG:'Healthcare', REGN:'Healthcare', VRTX:'Healthcare',
  BIIB:'Healthcare', ILMN:'Healthcare', IDXX:'Healthcare', MRNA:'Healthcare',
  DXCM:'Healthcare', PODD:'Healthcare', GEHC:'Healthcare', EW:'Healthcare',
  RMD:'Healthcare',  IQV:'Healthcare',  MTD:'Healthcare',  WAT:'Healthcare',
  ALGN:'Healthcare', INCY:'Healthcare', EXAS:'Healthcare', HOLX:'Healthcare',
  BDX:'Healthcare',  BAX:'Healthcare',  ZBH:'Healthcare',  HSIC:'Healthcare',
  VTRS:'Healthcare', CTLT:'Healthcare', PKI:'Healthcare',  A:'Healthcare',
  RVTY:'Healthcare', TECH:'Healthcare', NTRA:'Healthcare', VERACYTE:'Healthcare',
  VCYT:'Healthcare', NVST:'Healthcare', AMED:'Healthcare', AMEDISYS:'Healthcare',
  ACAD:'Healthcare', ACADIA:'Healthcare',ARWR:'Healthcare',ARROWHEAD:'Healthcare',
  BEAM:'Healthcare', CRSP:'Healthcare', EDIT:'Healthcare', NTLA:'Healthcare',
  FATE:'Healthcare', BLUE:'Healthcare', SGMO:'Healthcare', TWST:'Healthcare',
  CDNA:'Healthcare', NGENICS:'Healthcare',PACB:'Healthcare',RXRX:'Healthcare',
  SEER:'Healthcare', OLINK:'Healthcare', INAB:'Healthcare', CLVT:'Healthcare',
  SDGR:'Healthcare', AGEN:'Healthcare', AGIO:'Healthcare', AKBA:'Healthcare',
  ALKS:'Healthcare', ALLK:'Healthcare', ALNY:'Healthcare', ALPN:'Healthcare',
  ALEC:'Healthcare', ALXO:'Healthcare', AMLX:'Healthcare', AMRN:'Healthcare',
  ANAB:'Healthcare', ANPC:'Healthcare', APLS:'Healthcare', APRE:'Healthcare',
  ARCT:'Healthcare', ARDX:'Healthcare', ARGX:'Healthcare', ARAV:'Healthcare',
  ARQT:'Healthcare', ASND:'Healthcare', ATRC:'Healthcare', ATRS:'Healthcare',
  AUPH:'Healthcare', AVRO:'Healthcare', AXSM:'Healthcare', BBIO:'Healthcare',
  BCAB:'Healthcare', BCYC:'Healthcare', BDTX:'Healthcare', BFST:'Healthcare',
  BHVN:'Healthcare', BIOXCEL:'Healthcare',BIVI:'Healthcare',BLCM:'Healthcare',
  BMEA:'Healthcare', BNGO:'Healthcare', BNTX:'Healthcare', BPMC:'Healthcare',
  BSGM:'Healthcare', BTAI:'Healthcare', BYSI:'Healthcare', CABA:'Healthcare',
  CARA:'Healthcare', CBPO:'Healthcare', CCXI:'Healthcare', CDTX:'Healthcare',
  CERS:'Healthcare', CGEM:'Healthcare', CHRS:'Healthcare', CTIC:'Healthcare',
  CLDX:'Healthcare', CLFD:'Healthcare', CMRX:'Healthcare', CNTB:'Healthcare',
  CPRX:'Healthcare', CRNX:'Healthcare', CRVS:'Healthcare', CVAC:'Healthcare',
  CYCN:'Healthcare', DCPH:'Healthcare', DMTK:'Healthcare', DNLI:'Healthcare',
  DVAX:'Healthcare', EOLS:'Healthcare', EPZM:'Healthcare', ETON:'Healthcare',
  EVLO:'Healthcare', EVOK:'Healthcare', FOLD:'Healthcare', FOSL:'Healthcare',
  FULC:'Healthcare', FWBI:'Healthcare', GERN:'Healthcare', GLPG:'Healthcare',
  GMAB:'Healthcare', GRPH:'Healthcare', HALO:'Healthcare', HARP:'Healthcare',
  HOOK:'Healthcare', HRTX:'Healthcare', HZNP:'Healthcare', ICPT:'Healthcare',
  IFRX:'Healthcare', IGMS:'Healthcare', IMAB:'Healthcare', IMGO:'Healthcare',
  IMUX:'Healthcare', INVA:'Healthcare', IONS:'Healthcare', IOVA:'Healthcare',
  IRON:'Healthcare', ITCI:'Healthcare', JANX:'Healthcare', JAZZ:'Healthcare',
  KALA:'Healthcare', KALV:'Healthcare', KPTI:'Healthcare', KROS:'Healthcare',
  KRTX:'Healthcare', KYMR:'Healthcare', LGND:'Healthcare', LHCG:'Healthcare',
  LMNX:'Healthcare', LNTH:'Healthcare', LQDA:'Healthcare', LUMO:'Healthcare',
  MANH:'Healthcare', MCRB:'Healthcare', MDGL:'Healthcare', MERC:'Healthcare',
  MGNX:'Healthcare', MIRM:'Healthcare', MGTX:'Healthcare', MNKD:'Healthcare',
  MORF:'Healthcare', MRTX:'Healthcare', MRUS:'Healthcare', MYOVANT:'Healthcare',
  MYPS:'Healthcare', NKTR:'Healthcare', NKTX:'Healthcare', NMIH:'Healthcare',
  NOVN:'Healthcare', NRIX:'Healthcare', NUVB:'Healthcare', NVCR:'Healthcare',
  NVTA:'Healthcare', OLMA:'Healthcare', ONCT:'Healthcare', ORGO:'Healthcare',
  OTIC:'Healthcare', PBYI:'Healthcare', PCVX:'Healthcare', PDCO:'Healthcare',
  PHAT:'Healthcare', PNTM:'Healthcare', PRAX:'Healthcare', PRLD:'Healthcare',
  PRQR:'Healthcare', PTGX:'Healthcare', PTCT:'Healthcare', RARE:'Healthcare',
  RCUS:'Healthcare', RDUS:'Healthcare', RETA:'Healthcare', RGEN:'Healthcare',
  RLAY:'Healthcare', RMTI:'Healthcare', RNST:'Healthcare', RPRX:'Healthcare',
  RUBY:'Healthcare', RYTM:'Healthcare', SAGE:'Healthcare', SCPH:'Healthcare',
  SGEN:'Healthcare', SILK:'Healthcare', SLDB:'Healthcare', SLNO:'Healthcare',
  SMMT:'Healthcare', SPNV:'Healthcare', SRPT:'Healthcare', STVN:'Healthcare',
  SURF:'Healthcare', SWAV:'Healthcare', SYNH:'Healthcare', TALS:'Healthcare',
  TBPH:'Healthcare', TCRR:'Healthcare', TECH:'Healthcare', TENAX:'Healthcare',
  TMDX:'Healthcare', TMDI:'Healthcare', TNXP:'Healthcare', TPVG:'Healthcare',
  TPTX:'Healthcare', TRIL:'Healthcare', TRNX:'Healthcare', TVTX:'Healthcare',
  TYRA:'Healthcare', UFPT:'Healthcare', URGN:'Healthcare', UTMD:'Healthcare',
  VCEL:'Healthcare', VERA:'Healthcare', VKTX:'Healthcare', VNDA:'Healthcare',
  VRDN:'Healthcare', VRTV:'Healthcare', VYGR:'Healthcare', WVE:'Healthcare',
  XBIO:'Healthcare', XBIT:'Healthcare', XENE:'Healthcare', XERS:'Healthcare',
  ZGNX:'Healthcare', ZLAB:'Healthcare', ZNTL:'Healthcare', ZYME:'Healthcare',

  // ── Financials ──
  JPM:'Finance', BAC:'Finance', WFC:'Finance', GS:'Finance',
  MS:'Finance',  C:'Finance',   BLK:'Finance', SCHW:'Finance',
  AXP:'Finance', COF:'Finance', USB:'Finance', PNC:'Finance',
  TFC:'Finance', FITB:'Finance',KEY:'Finance', HBAN:'Finance',
  RF:'Finance',  CFG:'Finance', MTB:'Finance', ALLY:'Finance',
  DFS:'Finance', SYF:'Finance', V:'Finance',   MA:'Finance',
  MCO:'Finance', SPGI:'Finance',ICE:'Finance', CME:'Finance',
  CBOE:'Finance',MSCI:'Finance',NDAQ:'Finance',FDS:'Finance',
  AFL:'Finance', ALL:'Finance', AIG:'Finance', MET:'Finance',
  PRU:'Finance', TRV:'Finance', HIG:'Finance', CB:'Finance',
  PGR:'Finance', AON:'Finance', MMC:'Finance', WTW:'Finance',
  ACGL:'Finance',RNR:'Finance', EG:'Finance',  CINF:'Finance',
  GL:'Finance',  BRK:'Finance', BRKB:'Finance',CMA:'Finance',
  WTFC:'Finance',BOKF:'Finance',FHB:'Finance', PACW:'Finance',
  WAL:'Finance', FNB:'Finance', IBOC:'Finance',TCBI:'Finance',
  CVBF:'Finance',SFNC:'Finance',NBTB:'Finance',CTBI:'Finance',
  CBSH:'Finance',FFIN:'Finance',TRMK:'Finance',SBNY:'Finance',
  SBCF:'Finance',LBAI:'Finance',NYCB:'Finance',OCFC:'Finance',
  BUSE:'Finance',SRCE:'Finance',CCNE:'Finance',SVBFG:'Finance',
  FBIZ:'Finance',FBNC:'Finance',FCNCA:'Finance',FFBC:'Finance',
  FISI:'Finance',FMBI:'Finance',FNWB:'Finance',FXNC:'Finance',
  GBCI:'Finance',HFWA:'Finance',HOPE:'Finance',HTLF:'Finance',
  IBCP:'Finance',INDB:'Finance',ISTR:'Finance',JNNE:'Finance',
  KRNY:'Finance',LCNB:'Finance',LKFN:'Finance',MBWM:'Finance',
  MOFG:'Finance',NWIN:'Finance',ORRF:'Finance',OFG:'Finance',
  OBNK:'Finance',PFIS:'Finance',PNFP:'Finance',PPBI:'Finance',
  PRAA:'Finance',RNST:'Finance',SASR:'Finance',SBSI:'Finance',
  SMBC:'Finance',STBA:'Finance',TCBK:'Finance',TOWN:'Finance',
  TRST:'Finance',UBSH:'Finance',UCBI:'Finance',UMPQ:'Finance',
  UVSP:'Finance',VLY:'Finance', WABC:'Finance',WASH:'Finance',
  WSBC:'Finance',WSFS:'Finance',NRIM:'Finance',ESSA:'Finance',
  EVBN:'Finance',FBMS:'Finance',FWWW:'Finance',AMNB:'Finance',
  NECB:'Finance',AROW:'Finance',BSVN:'Finance',CBTX:'Finance',
  CLBK:'Finance',CTLP:'Finance',CZWI:'Finance',DCOM:'Finance',
  EMCF:'Finance',ESSA:'Finance',EVBG:'Finance',FINW:'Finance',
  CARE:'Finance',CATO:'Finance',CACC:'Finance',ECPG:'Finance',
  OMF:'Finance',  SLM:'Finance', NAVI:'Finance',NMFC:'Finance',
  FSK:'Finance',  ARCC:'Finance',GBDC:'Finance',MAIN:'Finance',
  GAIN:'Finance', HTGC:'Finance',BXSL:'Finance',PSEC:'Finance',
  TPVG:'Finance', PFLT:'Finance',NEWT:'Finance',CGBD:'Finance',
  CSWC:'Finance', PNNT:'Finance',TICC:'Finance',TCPC:'Finance',

  // ── Energy ──
  XOM:'Energy',  CVX:'Energy',  COP:'Energy',  EOG:'Energy',
  SLB:'Energy',  OXY:'Energy',  PSX:'Energy',  MPC:'Energy',
  VLO:'Energy',  PXD:'Energy',  DVN:'Energy',  HES:'Energy',
  HAL:'Energy',  BKR:'Energy',  FANG:'Energy', APA:'Energy',
  MRO:'Energy',  OVV:'Energy',  CTRA:'Energy', RRC:'Energy',
  EQT:'Energy',  AR:'Energy',   SM:'Energy',   MTDR:'Energy',
  TRGP:'Energy', WMB:'Energy',  KMI:'Energy',  OKE:'Energy',
  BP:'Energy',   SHEL:'Energy', TTE:'Energy',  E:'Energy',
  REGI:'Energy', CLNE:'Energy', PLUG:'Energy', FCEL:'Energy',
  BE:'Energy',   BLNK:'Energy', CHPT:'Energy', EVGO:'Energy',
  BEEM:'Energy', AMPE:'Energy', SUNW:'Energy', FLNC:'Energy',
  ARRY:'Energy', NOVA:'Energy', RUN:'Energy',  SPWR:'Energy',
  CSIQ:'Energy', JKS:'Energy',  DQ:'Energy',   SOL:'Energy',
  MAXN:'Energy', SEDG:'Energy', GNRC:'Energy', NOVA:'Energy',
  DUNE:'Energy', AMRC:'Energy', CWEN:'Energy', NEP:'Energy',
  AY:'Energy',   BEP:'Energy',  BEPC:'Energy', OPKO:'Energy',
  MPLX:'Energy', LNG:'Energy',  CQP:'Energy',  GLNG:'Energy',
  GLOG:'Energy', NFE:'Energy',  TELL:'Energy', NEXT:'Energy',
  RIG:'Energy',  VAL:'Energy',  DO:'Energy',   NE:'Energy',
  HP:'Energy',   PTEN:'Energy', NBR:'Energy',  LBRT:'Energy',
  NINE:'Energy', ACDC:'Energy', WTTR:'Energy', PUMP:'Energy',
  NRGV:'Energy', OIS:'Energy',  KOS:'Energy',  VAALCO:'Energy',
  MGY:'Energy',  CIVI:'Energy', CPE:'Energy',  CRGY:'Energy',
  COG:'Energy',  ESTE:'Energy', PDCE:'Energy', BATL:'Energy',
  REPX:'Energy', REX:'Energy',  SWN:'Energy',  CNX:'Energy',
  GPOR:'Energy', KGS:'Energy',  CRK:'Energy',  GRNT:'Energy',

  // ── Industrials ──
  BA:'Industrials',  CAT:'Industrials', GE:'Industrials',  HON:'Industrials',
  MMM:'Industrials', UPS:'Industrials', FDX:'Industrials', RTX:'Industrials',
  LMT:'Industrials', NOC:'Industrials', GD:'Industrials',  LHX:'Industrials',
  HII:'Industrials', TDG:'Industrials', CARR:'Industrials',OTIS:'Industrials',
  DE:'Industrials',  EMR:'Industrials', ETN:'Industrials', PH:'Industrials',
  ROK:'Industrials', IR:'Industrials',  SWK:'Industrials', AME:'Industrials',
  ITW:'Industrials', XYL:'Industrials', FAST:'Industrials',GWW:'Industrials',
  DOV:'Industrials', FTV:'Industrials', TT:'Industrials',  CPRT:'Industrials',
  VRSK:'Industrials',FLT:'Industrials', EXPD:'Industrials',CHRW:'Industrials',
  KNX:'Industrials', JBHT:'Industrials',WAB:'Industrials', GXO:'Industrials',
  J:'Industrials',   CSGP:'Industrials',RSG:'Industrials', WM:'Industrials',
  CTAS:'Industrials',RHI:'Industrials', MAN:'Industrials', AYI:'Industrials',
  PWR:'Industrials', MTZ:'Industrials', TTEK:'Industrials',EXPO:'Industrials',
  KFRC:'Industrials',HSII:'Industrials',HURN:'Industrials',ACCO:'Industrials',
  ADSW:'Industrials',AEIS:'Industrials',AIN:'Industrials', AL:'Industrials',
  ALK:'Industrials', ALGT:'Industrials',AAL:'Industrials', UAL:'Industrials',
  DAL:'Industrials', LUV:'Industrials', SAVE:'Industrials',JBLU:'Industrials',
  HA:'Industrials',  SKYW:'Industrials',MESA:'Industrials',SkyWest:'Industrials',
  ATSG:'Industrials',AAWW:'Industrials',AIRT:'Industrials',ECHO:'Industrials',
  HUBG:'Industrials',LSTR:'Industrials',ODFL:'Industrials',SAIA:'Industrials',
  ARCB:'Industrials',MRTN:'Industrials',USX:'Industrials', WERN:'Industrials',
  HTLD:'Industrials',CVLG:'Industrials',PTSI:'Industrials',RRTS:'Industrials',
  UNP:'Industrials', CSX:'Industrials', NSC:'Industrials', CP:'Industrials',
  CNI:'Industrials', KSU:'Industrials', GNWR:'Industrials',RAILQ:'Industrials',
  AZPN:'Industrials',CGNX:'Industrials',FLIR:'Industrials',MKSI:'Industrials',
  NOVT:'Industrials',RBC:'Industrials', SPB:'Industrials', TREX:'Industrials',
  BLDR:'Industrials',BECN:'Industrials',IBP:'Industrials', APOG:'Industrials',
  AWI:'Industrials', CSL:'Industrials', NCI:'Industrials', TILE:'Industrials',
  AAON:'Industrials',AIMD:'Industrials',AMWD:'Industrials',APYX:'Industrials',
  ARCOSA:'Industrials', ARC:'Industrials', ARCO:'Industrials',ARHS:'Industrials',
  ACNB:'Industrials', BCPC:'Industrials', BWXT:'Industrials',CDXS:'Industrials',
  CFX:'Industrials',  CLB:'Industrials',  CMCO:'Industrials',CW:'Industrials',
  DRS:'Industrials',  DXC:'Industrials',  ESAB:'Industrials',ESE:'Industrials',
  ESCO:'Industrials', ESNT:'Industrials', EVR:'Industrials', FBHS:'Industrials',
  FELE:'Industrials', GFF:'Industrials',  GEF:'Industrials', GNSS:'Industrials',
  GTLS:'Industrials', GWW:'Industrials',  HRI:'Industrials', HSC:'Industrials',
  HXL:'Industrials',  IIVI:'Industrials', IIIV:'Industrials',ITGR:'Industrials',
  JBT:'Industrials',  KAR:'Industrials',  KBAL:'Industrials',LMB:'Industrials',
  LNN:'Industrials',  MCRI:'Industrials', MDU:'Industrials', MMS:'Industrials',
  MRC:'Industrials',  MYRG:'Industrials', NGVT:'Industrials',NVT:'Industrials',
  OC:'Industrials',   ORN:'Industrials',  OSK:'Industrials', PCAR:'Industrials',
  PSIX:'Industrials', RXO:'Industrials',  SCCO:'Industrials',SKYW:'Industrials',
  SPXC:'Industrials', SXC:'Industrials',  TNET:'Industrials',TPC:'Industrials',
  TRNS:'Industrials', TRU:'Industrials',  TRN:'Industrials', UHAL:'Industrials',
  URI:'Industrials',  VMC:'Industrials',  WCN:'Industrials', WCC:'Industrials',
  WSC:'Industrials',  XPO:'Industrials',

  // ── Real Estate ──
  AMT:'Real Estate',  PLD:'Real Estate',  EQIX:'Real Estate', CCI:'Real Estate',
  SBAC:'Real Estate', DLR:'Real Estate',  PSA:'Real Estate',  EXR:'Real Estate',
  CBRE:'Real Estate', SPG:'Real Estate',  O:'Real Estate',    VICI:'Real Estate',
  WELL:'Real Estate', VTR:'Real Estate',  ARE:'Real Estate',  EQR:'Real Estate',
  AVB:'Real Estate',  ESS:'Real Estate',  MAA:'Real Estate',  UDR:'Real Estate',
  CPT:'Real Estate',  IRM:'Real Estate',  INVH:'Real Estate', AMH:'Real Estate',
  NNN:'Real Estate',  KIM:'Real Estate',  REG:'Real Estate',  BXP:'Real Estate',
  SLG:'Real Estate',  HIW:'Real Estate',  PDM:'Real Estate',  AIRC:'Real Estate',
  ACC:'Real Estate',  UE:'Real Estate',   NXRT:'Real Estate', NHI:'Real Estate',
  OHI:'Real Estate',  SBRA:'Real Estate', LTC:'Real Estate',  CTRE:'Real Estate',
  SNDA:'Real Estate', KRG:'Real Estate',  ROIC:'Real Estate', CBL:'Real Estate',
  MAC:'Real Estate',  WPG:'Real Estate',  PEI:'Real Estate',  AKR:'Real Estate',
  SRC:'Real Estate',  EPRT:'Real Estate', NTST:'Real Estate', FCPT:'Real Estate',
  ADC:'Real Estate',  GTY:'Real Estate',  PINE:'Real Estate', PSTL:'Real Estate',
  GOOD:'Real Estate', LAND:'Real Estate', SAFE:'Real Estate', IIPR:'Real Estate',
  PW:'Real Estate',   APLE:'Real Estate', CLDT:'Real Estate', CHSP:'Real Estate',
  CHATHAM:'Real Estate',SHO:'Real Estate',HST:'Real Estate',  PK:'Real Estate',
  RHP:'Real Estate',  NCLH:'Real Estate', XHR:'Real Estate',  BRSP:'Real Estate',
  EFC:'Real Estate',  KREF:'Real Estate', BXMT:'Real Estate', STWD:'Real Estate',
  TPG:'Real Estate',  GPMT:'Real Estate', ARI:'Real Estate',  RC:'Real Estate',
  TRTX:'Real Estate', WD:'Real Estate',   RITM:'Real Estate', NLY:'Real Estate',
  AGNC:'Real Estate', TWO:'Real Estate',  NYMT:'Real Estate', ORC:'Real Estate',
  CHMI:'Real Estate', EARN:'Real Estate', MFA:'Real Estate',  PMT:'Real Estate',

  // ── Materials ──
  LIN:'Materials', APD:'Materials', SHW:'Materials', ECL:'Materials',
  DD:'Materials',  DOW:'Materials', EMN:'Materials', CE:'Materials',
  ALB:'Materials', NEM:'Materials', FCX:'Materials', NUE:'Materials',
  STLD:'Materials',RS:'Materials',  AA:'Materials',  CLF:'Materials',
  MP:'Materials',  HUN:'Materials', RPM:'Materials', PPG:'Materials',
  IFF:'Materials', FMC:'Materials', CF:'Materials',  MOS:'Materials',
  NTR:'Materials', LYB:'Materials', PKG:'Materials', IP:'Materials',
  WRK:'Materials', BALL:'Materials',SEE:'Materials', AVY:'Materials',
  CCK:'Materials', AMCR:'Materials',BERY:'Materials',SLGN:'Materials',
  AEI:'Materials', AXTA:'Materials',GPRE:'Materials',HWKN:'Materials',
  KWR:'Materials', LAUR:'Materials',LXFR:'Materials',MEOH:'Materials',
  OLN:'Materials', POL:'Materials', TROX:'Materials',VNTR:'Materials',
  WLKP:'Materials',WLK:'Materials', ASIX:'Materials',AMS:'Materials',
  CENTA:'Materials',CMC:'Materials', GEO:'Materials', HAYN:'Materials',
  KALU:'Materials',MTRN:'Materials',PGTI:'Materials', RYI:'Materials',
  SCHN:'Materials',SXC:'Materials', SXQG:'Materials',VALE:'Materials',
  AG:'Materials',  EXK:'Materials', HL:'Materials',  MUX:'Materials',
  PAAS:'Materials',GPL:'Materials', USA:'Materials',  AEM:'Materials',
  AU:'Materials',  GFI:'Materials', KGC:'Materials',  HMY:'Materials',
  IAG:'Materials', MAG:'Materials', OR:'Materials',   SILV:'Materials',
  SSRM:'Materials',WPM:'Materials', KL:'Materials',   USAS:'Materials',

  // ── Utilities ──
  NEE:'Utilities', DUK:'Utilities', SO:'Utilities',  D:'Utilities',
  EXC:'Utilities', AEP:'Utilities', SRE:'Utilities', PCG:'Utilities',
  ED:'Utilities',  XEL:'Utilities', WEC:'Utilities', ES:'Utilities',
  AWK:'Utilities', FE:'Utilities',  ETR:'Utilities', PPL:'Utilities',
  CNP:'Utilities', NI:'Utilities',  AES:'Utilities', EVRG:'Utilities',
  PNW:'Utilities', AVA:'Utilities', OGE:'Utilities', MGEE:'Utilities',
  UIL:'Utilities', MSEX:'Utilities',SJW:'Utilities', YORW:'Utilities',
  CTWS:'Utilities',ARTNA:'Utilities',GWRS:'Utilities',UTMD:'Utilities',
  NWN:'Utilities', SR:'Utilities',  NJR:'Utilities', SWX:'Utilities',
  RGCO:'Utilities',GAS:'Utilities', ATO:'Utilities', ONE:'Utilities',
  SPKE:'Utilities',CLCO:'Utilities',CSWC:'Utilities',AGR:'Utilities',
  BIP:'Utilities', BIPC:'Utilities',NI:'Utilities',  IDACORP:'Utilities',
  POR:'Utilities', OTTR:'Utilities',CLNE:'Utilities', ALTUS:'Utilities',
  GNP:'Utilities', LAAG:'Utilities',NFYS:'Utilities', SPWR:'Utilities',

  // ── ETFs ──
  SPY:'ETF',   QQQ:'ETF',  IWM:'ETF',  DIA:'ETF',  VOO:'ETF',
  VTI:'ETF',   VEA:'ETF',  VWO:'ETF',  IVV:'ETF',  IWF:'ETF',
  IWD:'ETF',   IJH:'ETF',  IJR:'ETF',  GLD:'ETF',  SLV:'ETF',
  USO:'ETF',   UNG:'ETF',  TLT:'ETF',  IEF:'ETF',  SHY:'ETF',
  HYG:'ETF',   LQD:'ETF',  AGG:'ETF',  BND:'ETF',  BNDX:'ETF',
  XLK:'ETF',   XLF:'ETF',  XLV:'ETF',  XLE:'ETF',  XLI:'ETF',
  XLY:'ETF',   XLP:'ETF',  XLB:'ETF',  XLU:'ETF',  XLRE:'ETF',
  XLC:'ETF',   SOXX:'ETF', SMH:'ETF',  ARKK:'ETF', ARKG:'ETF',
  ARKW:'ETF',  ARKF:'ETF', ARKQ:'ETF', ARKX:'ETF', ARKI:'ETF',
  TQQQ:'ETF',  SQQQ:'ETF', SPXL:'ETF',SPXS:'ETF', UPRO:'ETF',
  SPXU:'ETF',  TECL:'ETF', TECS:'ETF', FNGU:'ETF', FNGD:'ETF',
  SOXL:'ETF',  SOXS:'ETF', LABU:'ETF', LABD:'ETF', UVXY:'ETF',
  SVXY:'ETF',  VXX:'ETF',  VIXY:'ETF', VIXM:'ETF', UVIX:'ETF',
  SVOL:'ETF',  GDX:'ETF',  GDXJ:'ETF', SIL:'ETF',  SILJ:'ETF',
  REMX:'ETF',  COPX:'ETF', URA:'ETF',  URNM:'ETF', BITO:'ETF',
  GBTC:'ETF',  ETHE:'ETF', BLOK:'ETF', DAPP:'ETF', BITQ:'ETF',
  MCHI:'ETF',  EEM:'ETF',  EWJ:'ETF',  EWZ:'ETF',  EWY:'ETF',
  EWG:'ETF',   EWU:'ETF',  EWA:'ETF',  EWC:'ETF',  EWL:'ETF',
  RSP:'ETF',   SCHD:'ETF', VIG:'ETF',  DVY:'ETF',  DGRO:'ETF',
  NOBL:'ETF',  JEPI:'ETF', JEPQ:'ETF', QYLD:'ETF', RYLD:'ETF',
  XYLD:'ETF',  NUSI:'ETF', DIVO:'ETF', SDIV:'ETF', PFFD:'ETF',
  KBWB:'ETF',  KRE:'ETF',  KBE:'ETF',  IAT:'ETF',  IAI:'ETF',
  IBB:'ETF',   XBI:'ETF',  ARKG:'ETF', GXLM:'ETF', CIBR:'ETF',
  HACK:'ETF',  BUG:'ETF',  CLOU:'ETF', SKYY:'ETF', WCLD:'ETF',
  IPAY:'ETF',  FINX:'ETF', KOIN:'ETF', ROBO:'ETF', BOTZ:'ETF',
  AIQ:'ETF',   LIT:'ETF',  DRIV:'ETF', KARS:'ETF', IDRV:'ETF',
  PSCT:'ETF',  IGV:'ETF',  IEDI:'ETF', FDN:'ETF',  PNQI:'ETF',
  VO:'ETF',    VB:'ETF',   VBR:'ETF',  VBK:'ETF',  VTV:'ETF',
  VONG:'ETF',  VONV:'ETF', VIOO:'ETF', VONE:'ETF', VTWO:'ETF',
  IWR:'ETF',   IWS:'ETF',  IWC:'ETF',  IWB:'ETF',  IWN:'ETF',
  IWO:'ETF',   IWP:'ETF',  IWV:'ETF',  ITOT:'ETF', IUSV:'ETF',
  IUSG:'ETF',  IUSB:'ETF', IAU:'ETF',  SGOL:'ETF', PHYS:'ETF',
  PSLV:'ETF',  CEF:'ETF',  SIVR:'ETF', PPLT:'ETF', PLTM:'ETF',

  // ── Crypto ──
  BTCUSD:'Crypto', ETHUSD:'Crypto',

  // ── Currency (top 10 most-traded forex pairs) ──
  EURUSD:'Currency', USDJPY:'Currency', GBPUSD:'Currency', USDCHF:'Currency',
  AUDUSD:'Currency', USDCAD:'Currency', NZDUSD:'Currency', EURJPY:'Currency',
  GBPJPY:'Currency', EURGBP:'Currency',

};
