// S&P 500 + NASDAQ 100 — ticker to GICS sector mapping
const SECTOR_MAP = {

  // ── Technology ──
  AAPL:'Technology', MSFT:'Technology', NVDA:'Technology', AVGO:'Technology',
  ORCL:'Technology', CSCO:'Technology', ADBE:'Technology', QCOM:'Technology',
  AMD:'Technology',  TXN:'Technology',  INTC:'Technology', IBM:'Technology',
  MU:'Technology',   AMAT:'Technology', LRCX:'Technology', KLAC:'Technology',
  ADI:'Technology',  MCHP:'Technology', NXPI:'Technology', STX:'Technology',
  WDC:'Technology',  HPQ:'Technology',  HPE:'Technology',  ACN:'Technology',
  INTU:'Technology', PAYX:'Technology', ADP:'Technology',  CDNS:'Technology',
  SNPS:'Technology', ANSS:'Technology', PTC:'Technology',  EPAM:'Technology',
  AKAM:'Technology', FFIV:'Technology', ENPH:'Technology', MPWR:'Technology',
  SWKS:'Technology', KEYS:'Technology', TRMB:'Technology', CDW:'Technology',
  CTSH:'Technology', IT:'Technology',   GEN:'Technology',  GDDY:'Technology',
  NET:'Technology',  PANW:'Technology', CRWD:'Technology', FTNT:'Technology',
  ZS:'Technology',   OKTA:'Technology', DDOG:'Technology', SNOW:'Technology',
  PLTR:'Technology', HUBS:'Technology', VEEV:'Technology', CRM:'Technology',
  NOW:'Technology',  WDAY:'Technology', MDB:'Technology',  SPLK:'Technology',
  PSTG:'Technology', TEAM:'Technology', BILL:'Technology', ESTC:'Technology',
  DOCU:'Technology', ZM:'Technology',   FSLR:'Technology', ROP:'Technology',
  JNPR:'Technology', NTAP:'Technology', TDY:'Technology',  ZBRA:'Technology',
  FIS:'Technology',  FISV:'Technology', WU:'Technology',   BR:'Technology',

  // ── Communication Services ──
  GOOG:'Communication', GOOGL:'Communication', META:'Communication',
  NFLX:'Communication', DIS:'Communication',   CMCSA:'Communication',
  T:'Communication',    VZ:'Communication',    TMUS:'Communication',
  CHTR:'Communication', PARA:'Communication',  WBD:'Communication',
  FOX:'Communication',  FOXA:'Communication',  NYT:'Communication',
  LYV:'Communication',  TTWO:'Communication',  EA:'Communication',
  RBLX:'Communication', SNAP:'Communication',  PINS:'Communication',
  SPOT:'Communication', TWLO:'Communication',  UBER:'Technology',
  LYFT:'Technology',    ROKU:'Communication',

  // ── Consumer Discretionary ──
  AMZN:'Consumer Disc', TSLA:'Consumer Disc', HD:'Consumer Disc',
  MCD:'Consumer Disc',  NKE:'Consumer Disc',  LOW:'Consumer Disc',
  SBUX:'Consumer Disc', TJX:'Consumer Disc',  BKNG:'Consumer Disc',
  CMG:'Consumer Disc',  MAR:'Consumer Disc',  HLT:'Consumer Disc',
  GM:'Consumer Disc',   F:'Consumer Disc',    RIVN:'Consumer Disc',
  LCID:'Consumer Disc', LVS:'Consumer Disc',  WYNN:'Consumer Disc',
  MGM:'Consumer Disc',  CZR:'Consumer Disc',  RCL:'Consumer Disc',
  CCL:'Consumer Disc',  NCLH:'Consumer Disc', ABNB:'Consumer Disc',
  EXPE:'Consumer Disc', EBAY:'Consumer Disc', ETSY:'Consumer Disc',
  LULU:'Consumer Disc', ROST:'Consumer Disc', BURL:'Consumer Disc',
  TGT:'Consumer Disc',  ANF:'Consumer Disc',  AEO:'Consumer Disc',
  GPS:'Consumer Disc',  URBN:'Consumer Disc', CPRI:'Consumer Disc',
  TPR:'Consumer Disc',  PVH:'Consumer Disc',  RL:'Consumer Disc',
  VFC:'Consumer Disc',  UAA:'Consumer Disc',  BBY:'Consumer Disc',
  ORLY:'Consumer Disc', AZO:'Consumer Disc',  TSCO:'Consumer Disc',
  DG:'Consumer Disc',   DLTR:'Consumer Disc', W:'Consumer Disc',

  // ── Consumer Staples ──
  WMT:'Consumer Staples', COST:'Consumer Staples', PG:'Consumer Staples',
  KO:'Consumer Staples',  PEP:'Consumer Staples',  PM:'Consumer Staples',
  MO:'Consumer Staples',  MDLZ:'Consumer Staples', KHC:'Consumer Staples',
  GIS:'Consumer Staples', K:'Consumer Staples',    CPB:'Consumer Staples',
  CAG:'Consumer Staples', SJM:'Consumer Staples',  HRL:'Consumer Staples',
  MKC:'Consumer Staples', CLX:'Consumer Staples',  CL:'Consumer Staples',
  CHD:'Consumer Staples', EL:'Consumer Staples',   ULTA:'Consumer Staples',
  SYY:'Consumer Staples', ADM:'Consumer Staples',  BG:'Consumer Staples',
  STZ:'Consumer Staples', TAP:'Consumer Staples',  SAM:'Consumer Staples',

  // ── Healthcare ──
  JNJ:'Healthcare',  UNH:'Healthcare',  LLY:'Healthcare',  ABBV:'Healthcare',
  MRK:'Healthcare',  PFE:'Healthcare',  TMO:'Healthcare',  ABT:'Healthcare',
  DHR:'Healthcare',  BMY:'Healthcare',  AMGN:'Healthcare', GILD:'Healthcare',
  CVS:'Healthcare',  MDT:'Healthcare',  SYK:'Healthcare',  BSX:'Healthcare',
  ELV:'Healthcare',  HUM:'Healthcare',  CI:'Healthcare',   CNC:'Healthcare',
  MOH:'Healthcare',  ISRG:'Healthcare', REGN:'Healthcare', VRTX:'Healthcare',
  BIIB:'Healthcare', ILMN:'Healthcare', IDXX:'Healthcare', MRNA:'Healthcare',
  DXCM:'Healthcare', PODD:'Healthcare', GEHC:'Healthcare', EW:'Healthcare',
  RMD:'Healthcare',  IQV:'Healthcare',  MTD:'Healthcare',  WAT:'Healthcare',
  ALGN:'Healthcare', INCY:'Healthcare', EXAS:'Healthcare', HOLX:'Healthcare',
  BDX:'Healthcare',  BAX:'Healthcare',  ZBH:'Healthcare',  HSIC:'Healthcare',
  VTRS:'Healthcare', CTLT:'Healthcare', PKI:'Healthcare',  A:'Healthcare',

  // ── Financials ──
  JPM:'Finance', BAC:'Finance', WFC:'Finance', GS:'Finance',
  MS:'Finance',  C:'Finance',   BLK:'Finance', SCHW:'Finance',
  AXP:'Finance', COF:'Finance', USB:'Finance', PNC:'Finance',
  TFC:'Finance', FITB:'Finance',KEY:'Finance', HBAN:'Finance',
  RF:'Finance',  CFG:'Finance', MTB:'Finance', ALLY:'Finance',
  DFS:'Finance', SYF:'Finance', V:'Finance',   MA:'Finance',
  MCO:'Finance', SPGI:'Finance',ICE:'Finance', CME:'Finance',
  CBOE:'Finance',MSCI:'Finance',NDAQ:'Finance',FDS:'Finance',
  AFL:'Finance', ALL:'Finance', AIG:'Finance', MET:'Finance',
  PRU:'Finance', TRV:'Finance', HIG:'Finance', CB:'Finance',
  PGR:'Finance', AON:'Finance', MMC:'Finance', WTW:'Finance',
  ACGL:'Finance',RNR:'Finance', EG:'Finance',  CINF:'Finance',
  GL:'Finance',  BRK:'Finance', FRC:'Finance', CMA:'Finance',

  // ── Energy ──
  XOM:'Energy',  CVX:'Energy',  COP:'Energy',  EOG:'Energy',
  SLB:'Energy',  OXY:'Energy',  PSX:'Energy',  MPC:'Energy',
  VLO:'Energy',  PXD:'Energy',  DVN:'Energy',  HES:'Energy',
  HAL:'Energy',  BKR:'Energy',  FANG:'Energy', APA:'Energy',
  MRO:'Energy',  OVV:'Energy',  CTRA:'Energy', RRC:'Energy',
  EQT:'Energy',  AR:'Energy',   SM:'Energy',   MTDR:'Energy',
  TRGP:'Energy', WMB:'Energy',  KMI:'Energy',  OKE:'Energy',
  EP:'Energy',   BP:'Energy',   SHEL:'Energy',

  // ── Industrials ──
  BA:'Industrials',  CAT:'Industrials', GE:'Industrials',  HON:'Industrials',
  MMM:'Industrials', UPS:'Industrials', FDX:'Industrials', RTX:'Industrials',
  LMT:'Industrials', NOC:'Industrials', GD:'Industrials',  LHX:'Industrials',
  HII:'Industrials', TDG:'Industrials', CARR:'Industrials',OTIS:'Industrials',
  DE:'Industrials',  EMR:'Industrials', ETN:'Industrials', PH:'Industrials',
  ROK:'Industrials', IR:'Industrials',  SWK:'Industrials', AME:'Industrials',
  ITW:'Industrials', XYL:'Industrials', FAST:'Industrials',GWW:'Industrials',
  DOV:'Industrials', FTV:'Industrials', TT:'Industrials',  CPRT:'Industrials',
  VRSK:'Industrials',FLT:'Industrials', EXPD:'Industrials',CHRW:'Industrials',
  KNX:'Industrials', JBHT:'Industrials',WAB:'Industrials', GXO:'Industrials',
  J:'Industrials',   CSGP:'Industrials',RSG:'Industrials', WM:'Industrials',
  CTAS:'Industrials',RHI:'Industrials', MAN:'Industrials', AYI:'Industrials',
  PWR:'Industrials', MTZ:'Industrials', TTEK:'Industrials',

  // ── Real Estate ──
  AMT:'Real Estate',  PLD:'Real Estate',  EQIX:'Real Estate', CCI:'Real Estate',
  SBAC:'Real Estate', DLR:'Real Estate',  PSA:'Real Estate',  EXR:'Real Estate',
  CBRE:'Real Estate', SPG:'Real Estate',  O:'Real Estate',    VICI:'Real Estate',
  WELL:'Real Estate', VTR:'Real Estate',  ARE:'Real Estate',  EQR:'Real Estate',
  AVB:'Real Estate',  ESS:'Real Estate',  MAA:'Real Estate',  UDR:'Real Estate',
  CPT:'Real Estate',  IRM:'Real Estate',  INVH:'Real Estate', AMH:'Real Estate',
  NNN:'Real Estate',  KIM:'Real Estate',  REG:'Real Estate',  BXP:'Real Estate',

  // ── Materials ──
  LIN:'Materials', APD:'Materials', SHW:'Materials', ECL:'Materials',
  DD:'Materials',  DOW:'Materials', EMN:'Materials', CE:'Materials',
  ALB:'Materials', NEM:'Materials', FCX:'Materials', NUE:'Materials',
  STLD:'Materials',RS:'Materials',  AA:'Materials',  CLF:'Materials',
  MP:'Materials',  HUN:'Materials', RPM:'Materials', PPG:'Materials',
  IFF:'Materials', FMC:'Materials', CF:'Materials',  MOS:'Materials',
  NTR:'Materials', LYB:'Materials', PKG:'Materials', IP:'Materials',
  WRK:'Materials', BALL:'Materials',SEE:'Materials', AVY:'Materials',
  CCK:'Materials',

  // ── Utilities ──
  NEE:'Utilities', DUK:'Utilities', SO:'Utilities',  D:'Utilities',
  EXC:'Utilities', AEP:'Utilities', SRE:'Utilities', PCG:'Utilities',
  ED:'Utilities',  XEL:'Utilities', WEC:'Utilities', ES:'Utilities',
  AWK:'Utilities', FE:'Utilities',  ETR:'Utilities', PPL:'Utilities',
  CNP:'Utilities', NI:'Utilities',  AES:'Utilities', EVRG:'Utilities',
  PNW:'Utilities', AVA:'Utilities', OGE:'Utilities',
};
